### ISSUE TITLE
Allow updating name of nodes after insertion

### ISSUE THREAD

**Issue by holly-hacker** [Washi1337/Rivers#10]
When editing nodes after inserting them in a graph, their names may become outdated. It would be nice to have a way of updating the name of an individual node, or of all of them at once.

**Comment by holly-hacker** [comment]
To be clear: for my usecase simply updating the name to the ToString implementation of the Node (and throwing on duplicates) would be fine. It's just that the names initially assigned to the nodes aren't up to date anymore so the generated .dot file can contain less relevant information.

It's also an option to just assign the description or name property and use that, I guess. I didn't really think of that when creating this issue but I'll keep this open so you can evaluate for yourself.

**Comment by Washi1337** [comment]
The problem is that the names of nodes are used as keys in the internal data structure of the graph. Not only the nodes themselves are indexed this way, but also each neighbour of a node is. Updating names is therefore a very expensive task (O(n^2)). 

If you just want to change the display name of the node,  change the label of the node in UserData.

**Comment by holly-hacker** [comment]
Yeah, seems fair to me.
